name: Deploy to IBM CF

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 1 * * 1
   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IBM Cloud Foundry
        # You may pin to the exact commit or the version.
        uses: subhamx/ibm-cloud-foundry-deploy@master
        with:
          # For Users who have opted for Authentication using Email & Password
    
          # For Users who have opted for Authentication using API KEY
          API_KEY: ${{ secrets.IBM_API_KEY }}
          # Cloud Foundry API Endpoint
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
          # Path to manifest.yml
          MANIFEST_FILE_PATH: 'manifest.yml'
          # Cloud Foundry ORG Name
          ORG: ${{ secrets.ORG }}
          # Cloud Foundry Space Name for the specified ORG
          SPACE: ${{ secrets.SPACE }}
